apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: load-test
spec:
  metrics:
  - name: load-test
    interval: 5m
    successCondition: result[0] <= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.linkerd-viz.svc.cluster.local:9090
        query: |
          sum(irate(response_total{classification="success", namespace="default", direction="inbound", app="example-argocd-canary-linkerd"}[5m])) by (deployment) / sum(irate(response_total{namespace="default", direction="inbound", app="example-argocd-canary-linkerd"}[5m]))