kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: load-test
spec:
  metrics:
    - name: pass
      provider:
        job:
          spec:
            template:
              spec:
                containers:
                  - name: load-tester
                    args:
                      - |
                        wrk -t10 -c40 -d45s -s report.lua http://release-name-example-argocd-canary-linkerd.{{ args.namespace }}.svc/color
                        jq -e '.errors_ratio <= 0.35 and .latency_avg_ms < 100' report.json