apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: release-name-example-argocd-canary-linkerd
spec:
  strategy:
    canary:
      trafficRouting:
        smi:
          rootService: rollout-linkerd
      trafficManagement:
        $patch: delete