apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: release-name-example-argocd-canary-linkerd
spec:
  strategy:
    canary:
      analysis:
        templates:
        - templateName: load-test
        args:
        - name: namespace
          value: default
      canaryService: release-name-example-argocd-canary-linkerd-canary
      stableService: release-name-example-argocd-canary-linkerd-stable
      trafficRouting:
        smi:
          rootService: rollout-linkerd
      trafficManagement:
        $patch: delete