apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: release-name-example-argocd-canary-linkerd
spec:
  strategy:
    canary:
      canaryService: release-name-example-argocd-canary-linkerd-canary
      stableService: release-name-example-argocd-canary-linkerd-stable
      trafficRouting:
        smi:
          rootService: rollout-linkerd
      trafficManagement:
        $patch: delete